### ISSUE TITLE
master branch failed on starting up by command " gulp watch"

### ISSUE THREAD

**Issue by mingqin1** [aurelia-ui-toolkits/aurelia-v-grid#57]
My environments: Node v6.6.0;  NPM v3.10.3; gulp -v CLI version 3.9.1.

I followed below instructions to get and run the master

1: Download git clone https://github.com/aurelia-ui-toolkits/aurelia-v-grid
2: Run npm install in under root folder and under "sample"
3: Run jspm install under root folder and under "sample"
4: Run gulp watch watch under the sample folder.

Once I run "gulp watch" under directory -C:\Demos\temp\aurelia-v-grid\sample, I got following errors

_[16:29:05] Working directory changed to C:\demos\temp\aurelia-v-grid
[16:29:14] Using gulpfile C:\demos\temp\aurelia-v-grid\gulpfile.js
[16:29:14] Starting 'build'...
[16:29:14] Starting 'clean'...
[16:29:14] Finished 'clean' after 12 ms
[16:29:14] Starting 'build-index'...
[16:29:14] Finished 'build-index' after 123 ms
[16:29:14] Starting 'build-es6-temp'...
[16:29:14] Starting 'build-es6'...
[16:29:14] Starting 'build-commonjs'...
[16:29:14] Starting 'build-amd'...
[16:29:14] Starting 'build-system'...
[16:29:14] Starting 'build-dev'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: C:/demos/temp/aurelia-v-grid/devbuild/aurelia-v-grid.js: `configure` has already been exported. Exported id
  34 | }
  35 |
> 36 | export function configure(config) {
     | ^
  37 |   config.globalResources(
  38 |     'vGrid/v-grid-element-footer-pager',
  39 |     'vGrid/v-grid-element-row-repeat',
    at Parser.pp.raise (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\parser\location.js
    at Parser.pp.raiseDuplicateExportError (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\li
    at Parser.pp.checkDuplicateExports (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\pa
    at Parser.pp.checkExport (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\parser\state
    at Parser.pp.parseExport (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\parser\state
    at Parser.parseExport (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\plugins\flow.js
    at Parser.pp.parseStatement (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\parser\st
    at Parser.parseStatement (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\plugins\flow
    at Parser.pp.parseBlockBody (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\parser\st
    at Parser.pp.parseTopLevel (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\parser\sta
    at Parser.parse (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\parser\index.js:96:17
    at parse (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babylon\lib\index.js:45:47)
    at File.parse (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\
    at File.parseCode (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\f
    at C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\pipeline.js:49:12
    at File.wrap (C:\demos\temp\aurelia-v-grid\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\i
PS C:\demos\temp\aurelia-v-grid\sample>_

**Comment by vegarringdal** [comment]
Ill have a look at this when I get home from work.
This prb just is the demo thats broken, dunno why atm.
Usage by installing prb will work.

**Comment by vegarringdal** [comment]
If you want to try something before I get a chance to look at it you could try this
* delete the plugin.js under src folder on root /or comment out the code
* ```run build-release```
* then run ```gulp watch```

Just noticed this:
>yntaxError: C:/demos/temp/aurelia-v-grid/devbuild/aurelia-v-grid.js: configure has already been exported. Exported id

only the plugin.js that also have the configure also, so it could be this, but never had issues with it

**Comment by vegarringdal** [comment]
found the problem, just merged a fix.
Dunno why I didnt get the error on local copy, but some internals have changed I guess, so I cant have the "plugin.js" in folder anymore

**Comment by mingqin1** [comment]
vegarringdal : thanks
